apiVersion: v1
kind: ImageStream
metadata:
  name: fuse-java-openshift
spec:
  tags:
  - name: "latest"
    annotations:
      description: Fabric8 Java S2I images.
      iconClass: icon-jboss
      supports: 'jboss-fuse:7,java:8,xpaas:1.2'
      tags: 'builder,jboss-fuse,java,xpaas,hidden'
      version: '1.0'
    from:
      kind: DockerImage
      name: ${BUILDER_IMAGE_NAME}
---
apiVersion: v1
kind: ImageStream
metadata:
  name: greetings-service
spec: {}
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: greetings-service
  labels:
    app: fuse-circuit-breaker-mission-greetings-service
    group: com.redhat.fuse.boosters
    provider: fabric8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: greetings-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: ${SOURCE_REPOSITORY_URL}
      ref: ${SOURCE_REPOSITORY_REF}
      #contextDir: ${SOURCE_REPOSITORY_DIR}
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_COPY_ARGS
          value: "${ARTIFACT_COPY_ARGS}"
      forcePull: true
      from:
        kind: ImageStreamTag
        name: fuse-java-openshift:latest
      incremental: true
    type: Source
  triggers:
  - github:
      secret: ${GITHUB_WEBHOOK_SECRET}
    type: GitHub
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0